[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend && npm ci --only=production"]

[phases.build]
cmds = ["cd backend && npm run build", "cd backend && npm run migrate"]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production" 