name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Cloudflare Pages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        working-directory: ./frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          # Créer un fichier wrangler.toml pour le déploiement
          cat > wrangler.toml << EOF
          name = "paloma-9sq"
          compatibility_date = "2024-01-01"
          
          [site]
          bucket = "./dist"
          EOF
          
          # Installer Wrangler
          npm install -g wrangler
          
          # Déployer avec Wrangler
          wrangler pages deploy dist --project-name=paloma-9sq 
